import numpy as np

# --- T-NORMS (Triangular Norms) ---
def t_M(x, y): return np.minimum(x, y)
def t_P(x, y): return x * y
def t_L(x, y): return np.maximum(0, x + y - 1)
def t_D(x, y): return np.where(x == 1, y, np.where(y == 1, x, 0))
def t_FD(x, y): return np.where(x + y <= 1, 0, np.minimum(x, y))

# --- S-CONORMS (Triangular Conorms) ---
def s_M(x, y): return np.maximum(x, y)
def s_P(x, y): return x + y - (x * y)
def s_L(x, y): return np.minimum(1, x + y)
def s_D(x, y): return np.where(x == 0, y, np.where(y == 0, x, 1))
def s_FD(x, y): return np.where(x + y >= 1, 1, np.maximum(x, y))

# --- INDUCED IMPLICATIONS ---
def imp_T_M(a, b): return np.where(a <= b, 1.0, b)
def imp_T_P(a, b):
    with np.errstate(divide='ignore', invalid='ignore'):
        res = np.where(a <= b, 1.0, b / a)
        res = np.where(a == 0, 1.0, res)
    return res
def imp_T_L(a, b): return np.minimum(1, 1 - a + b)
def imp_T_FD(a, b):
    """Implication induced by T_FD (Fodor implication)"""
    return np.where(a <= b, 1.0, np.maximum(1 - a, b))

# --- DUAL IMPLICATIONS ---
def dual_imp_S_M(a, b):
    """Dual induced implication generated by S_M (maximum)."""
    return np.where(a >= b, 0.0, b)

def dual_imp_S_P(a, b):
    """Dual induced implication generated by S_P (Probabilistic sum)."""
    with np.errstate(divide='ignore', invalid='ignore'):
        res = np.where(a >= b, 0.0, (b - a) / (1.0 - a))
    return res

def dual_imp_S_L(a, b):
    """Dual induced implication generated by S_L (Lukasiewicz)."""
    return np.maximum(0.0, b - a)


def dual_imp_T_P(a, b):
    """Dual induced implication generated by T_P (Product)."""
    with np.errstate(divide='ignore', invalid='ignore'):
        res = np.where(a != 0, b / a, 0.0)
    return res

def dual_imp_T_L(a, b):
    """Dual induced implication generated by T_L (Lukasiewicz)."""
    return np.where(b != 0, np.minimum(1.0, 1.0 - a + b), 0.0)

def dual_imp_T_M(a, b):
    """Dual induced implication generated by T_M (Minimum)."""
    return b

# --- CUSTOM OPERATIONS FOR PAPER EXAMPLE 11 ---
def op_EX1(a, b): return a * np.minimum(a, b)
def IMP_EX1(a, b):
    with np.errstate(divide='ignore', invalid='ignore'):
        res = np.where(a**2 <= b, 1.0, b / a)
    return res
def DIMP_EX1(a, b):
    with np.errstate(divide='ignore', invalid='ignore'):
        res = np.where(a**2 > b, b / a, a)
    return res

NORM_MAP = {
    'T_M': t_M, 'T_P': t_P, 'T_L': t_L, 'T_D': t_D, 'T_FD': t_FD,
    'S_M': s_M, 'S_P': s_P, 'S_L': s_L, 'S_D': s_D, 'S_FD': s_FD,
    'IMP_T_M': imp_T_M, 'IMP_T_P': imp_T_P, 'IMP_T_L': imp_T_L, 'IMP_T_FD': imp_T_FD,
    'DIMP_S_M': dual_imp_S_M, 'DIMP_S_P': dual_imp_S_P, 'DIMP_S_L': dual_imp_S_L,
    'DIMP_T_P': dual_imp_T_P, 'DIMP_T_L': dual_imp_T_L, 'DIMP_T_M': dual_imp_T_M,
    'OP_EX1': op_EX1, 'IMP_EX1': IMP_EX1, 'DIMP_EX1': DIMP_EX1,
}

def get_operator(identifier):
    if callable(identifier): return identifier
    if isinstance(identifier, str):
        key = identifier.upper()
        if key == 'MIN': key = 'T_M'
        if key == 'MAX': key = 'S_M'
        if key in NORM_MAP:
            return NORM_MAP[key]
    raise ValueError(f"Norm '{identifier}' not found in registry. Please use paper notation.")